In [120]:
import os
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [121]:
a = [[1,2,3,4,5,6,7],[7,6,5,4,3,2,1],[4,5,6,7,1,2,3],[1,2,3,4,5,6,7],[7,6,5,4,3,2,1],[4,5,6,7,1,2,3],[1,2,3,4,5,6,7],[7,6,5,4,3,2,1],[4,5,6,7,1,2,3],]

In [122]:
nd_a = np.array(a)

In [123]:
np.array(a)

array([[1, 2, 3, 4, 5, 6, 7],
       [7, 6, 5, 4, 3, 2, 1],
       [4, 5, 6, 7, 1, 2, 3],
       [1, 2, 3, 4, 5, 6, 7],
       [7, 6, 5, 4, 3, 2, 1],
       [4, 5, 6, 7, 1, 2, 3],
       [1, 2, 3, 4, 5, 6, 7],
       [7, 6, 5, 4, 3, 2, 1],
       [4, 5, 6, 7, 1, 2, 3]])

In [124]:
print(nd_a)

[[1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]
 [4 5 6 7 1 2 3]
 [1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]
 [4 5 6 7 1 2 3]
 [1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]
 [4 5 6 7 1 2 3]]


In [141]:
eventwo = nd_a[:,0] >= 2
first = nd_a[:,0]
second = nd_a[:,1]

In [126]:
print(eventwo)

[False  True  True False  True  True False  True  True]


In [148]:

filtered = nd_a[eventwo]

In [149]:
base = np.zeros(len(nd_a))

In [150]:
base

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [151]:
first

array([ 8,  3, 28, 20,  6, 49, 32,  4,  4])

In [152]:
base[first>second]=1

In [153]:
base

array([0., 0., 1., 0., 0., 1., 0., 0., 0.])

In [154]:
#Took this next part of code from a website to get the colors of each value. This is only for visual distinction, and nothing too important.
# We'll color code by height, but you could use any scalar
#fracs = y / y.max()

# we need to normalize the data to 0..1 for the full range of the colormap
#norm = colors.Normalize(fracs.min(), fracs.max())

# Now, we'll loop through our objects and set the color of each accordingly
#for thisfrac, thispatch in zip(fracs, patches):
#    color = plt.cm.viridis(norm(thisfrac))
#    thispatch.set_facecolor(color)